DROP DATABASE IF EXISTS model_example;

CREATE DATABASE model_example;

CREATE TABLE users 
(
	id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  email VARCHAR(50) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  PRIMARY KEY (id)
);